server:
  port: 80
spring:
  application:
    name: buytickets
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///spider_bilibili?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
logging:
  level:
    com.yuan: error